server {
	# Listen on port 443 for SSL connections
	listen 443 ssl;
	
	# Define the server name
	server_name mcruz-sa.42.fr;
	
	# SSL certificate configuration
	ssl_certificate		/run/secrets/mcruz-sa_cert;
	ssl_certificate_key /run/secrets/mcruz-sa_key;

	# SSL protocols and ciphers
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
}