services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    secrets:
      - mcruz-sa_cert
      - mcruz-sa_key
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    secrets:
      - root_password
      - user_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/user_password
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "3306"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    secrets:
      - user_password
      - root_password
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${MYSQL_DB}
      - WP_DB_USER=${MYSQL_USER}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER_NAME=${WP_USER_NAME}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_ROLE=${WP_USER_ROLE}
      - WP_DB_PASSWORD_FILE=/run/secrets/user_password
      - WP_USER_PASS_FILE=/run/secrets/user_password
      - WP_ADMIN_PASS_FILE=/run/secrets/root_password
    networks:
      - inception
    restart:
      always
  

secrets:
  mcruz-sa_cert:
    file: ./requirements/nginx/ssl/mcruz-sa.42.fr.crt
  mcruz-sa_key:
    file: ./requirements/nginx/ssl/mcruz-sa.42.fr.key
  root_password:
    file: ./secrets/root_password.txt
  user_password:
    file: ./secrets/user_password.txt

volumes:
  db-data:
    name: mariadb
  wordpress:
    name: wordpress

networks:
  inception:
    name: inception